In [1]:
import numpy as np

In [2]:
a = np.array([[3,2],[1,3]])
b = np.array([[2,2],[1,2]])

In [3]:
np.dot(a,b)

array([[ 8, 10],
       [ 5,  8]])

In [4]:
np.vdot(a,b)

17

In [5]:
a = np.arange(6).reshape((2,3))
b = np.arange(3)
np.inner(a,b)

array([ 5, 14])

In [6]:
m = np.diag([4,3,2,1])

In [7]:
np.linalg.eig(m)

(array([4., 3., 2., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [9]:
np.linalg.det(m)

24.000000000000004

In [15]:
m = np.array([[3,1,],[1,2]])
result = np.array([9,9])

3 * x0 + 1 * x1 = 9

1 * x0 + 2 * x1 = 8

In [16]:
x = np.linalg.solve(m,result)
x

array([1.8, 3.6])