In [1]:
import numpy as np

Ejercicio 1

Genera un array que contenga 25 elementos entre 0 y 99 siguiendo una distribución lineal. Luego, transforma ese array en una matriz de 5 x 5. ¿Cuál es la diagonal de la matriz? ¿Y la diagonal justo superior?

In [5]:
arr = np.linspace(0,100, num=25, endpoint=False)
arr

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [8]:
m = arr.reshape((5,5))
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.]])

In [9]:
np.diag(m)

array([ 0., 24., 48., 72., 96.])

In [10]:
np.diag(m,k=1)

array([ 4., 28., 52., 76.])

Ejercicio 2

Crea un de 5 x 4 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir dos nuevas matrices, una de 5 x 9, y otra de 9 x 5.

In [27]:
m1 = np.repeat(10, 20).reshape(5,4)
m1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [28]:
np.concatenate((m,m1.T), axis= 0)

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [29]:
np.concatenate((m,m1), axis = 1)

array([[ 0.,  4.,  8., 12., 16., 10., 10., 10., 10.],
       [20., 24., 28., 32., 36., 10., 10., 10., 10.],
       [40., 44., 48., 52., 56., 10., 10., 10., 10.],
       [60., 64., 68., 72., 76., 10., 10., 10., 10.],
       [80., 84., 88., 92., 96., 10., 10., 10., 10.]])

Ejercicio 3

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array:

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?

In [42]:
a = np.array(['     este es un curso de openwebinars    '])
a = np.char.strip(a)
a

array(['este es un curso de openwebinars'], dtype='<U41')

In [43]:
a = np.char.split(a,sep=' ')
a

array([list(['este', 'es', 'un', 'curso', 'de', 'openwebinars'])],
      dtype=object)

In [46]:
a = np.char.capitalize(a[0])
a

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

In [48]:
a[np.char.startswith(a,'E')]

array(['Este', 'Es'], dtype='<U12')

Ejercicio 4

Considerando las matrices A y B.

A: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; B:

    3 1 2      2 0 3
 
    4 1 3      1 1 1

    2 0 1      0 2 4

Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?

Realiza la multiplicación de la matriz A x 2

¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [54]:
A = np.matrix([[3,1,2],[4,1,3],[2,0,1]])
B = np.matrix([[2,0,3],[1,1,1],[0,2,4]])
print(A,'\n\n',B)

[[3 1 2]
 [4 1 3]
 [2 0 1]] 

 [[2 0 3]
 [1 1 1]
 [0 2 4]]


In [55]:
np.dot(A,B) == np.dot(B,A)

matrix([[False, False, False],
        [ True, False, False],
        [False,  True,  True]])

In [57]:
np.dot(A,2)

matrix([[6, 2, 4],
        [8, 2, 6],
        [4, 0, 2]])

In [58]:
np.vdot(A,B) == np.vdot(B,A)

matrix([[ True]])

Ejercicio 5

Usando la matriz A del ejercicio anterior, calcula:

A^3

El determinante de A

Resuelve la ecuación Ax = y, siendo *y* el array [3,2,5]

In [59]:
np.power(A,3)

matrix([[27,  1,  8],
        [64,  1, 27],
        [ 8,  0,  1]], dtype=int32)

In [61]:
np.linalg.matrix_power(A,3) # esta es correcta. mismo que A ** 3

matrix([[ 89,  21,  57],
        [114,  27,  73],
        [ 42,  10,  27]])

In [62]:
np.linalg.det(A)

1.0

In [64]:
np.linalg.solve(A,[3,2,5])

array([ 6., -1., -7.])