In [1]:
import numpy as np

In [7]:
np.round([4.5,6.1056,6.105],2)

array([4.5 , 6.11, 6.1 ])

In [8]:
np.prod([2,3,4])

24

In [11]:
b = np.array([[2,3,4],[2,2,2]])
print(np.prod(b), np.prod(b, axis=0), np.prod(b, axis=1))

192 [4 6 8] [24  8]


In [12]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [20]:
np.isclose(np.exp(b),np.power(np.e,b), rtol=0.000000001)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [21]:
np.log(np.exp(b))

array([[2., 3., 4.],
       [2., 2., 2.]])