In [1]:
import numpy as np

In [3]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.min(arr, axis=0)

array([0, 1, 2, 3])

In [5]:
np.min(arr, axis=1)

array([0, 4, 8])

In [7]:
b = np.arange(102,9872,3)
np.percentile(b,13)

1371.8400000000001

In [9]:
np.quantile(b, q= 0.25)

2544.0

In [11]:
c = np.array([1,2,0,100,200,300])
np.mean(c) # media normal

100.5

In [12]:
np.median(c)

51.0

In [13]:
# desviacion = sqrt(varianza)
np.std(b)

2820.6446071775863

In [14]:
np.sqrt(np.var(b))

2820.6446071775863