In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[4,3,2,1]])
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
f = [1.5,2.7,3.9]
np.asarray(f).dtype

dtype('float64')

In [14]:
np.repeat([[10,20,30],[40,50,60]],repeats=10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 60,
       60, 60, 60, 60, 60, 60, 60, 60, 60])

In [20]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[4,3,2,1]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1]])

In [24]:
a = np.array([5,6,7,8])
b = np.array([4,3,2,1])
np.stack((a,b), axis = 1)

array([[5, 4],
       [6, 3],
       [7, 2],
       [8, 1]])

In [28]:
a = np.array([5,6,7,8])
np.insert(a,obj=0,values=[9,0])

array([9, 0, 5, 6, 7, 8])