In [1]:
import numpy as np

In [3]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
np.full((4,4),fill_value=[10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [19]:
np.fromstring('1 2 3 4 5 6',sep=' ',dtype='int').reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.linspace(start=2,stop=3.5, num=10, endpoint=True, retstep=True)

(array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
        2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ]),
 0.16666666666666666)

In [41]:
np.logspace(start=2, stop=3.5, num = 10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

In [42]:
np.diag(a,k=-1)

array([4, 9])

In [43]:
np.diagflat([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [47]:
np.tri(5,5, )

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])