In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6], dtype = 'int')

In [3]:
array1.dtype

dtype('int32')

In [5]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin = 2)

In [6]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array3 = np.array([1,2,3], dtype = 'complex')

In [13]:
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((4,2), dtype = 'int')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [17]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [18]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])