In [1]:
import numpy as np

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.shape

(10,)

In [6]:
a[1:9:2]

array([1, 3, 5, 7])

In [7]:
a[-2:]

array([8, 9])

In [8]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
a = np.array([[1,2,3],[4,5,6]], dtype = np.int8)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [12]:
a[1,2]

6

In [21]:
a[0:2:1,1:2:1]

array([[2],
       [5]], dtype=int8)

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
a[a>4]

array([5, 6, 7, 8, 9])

In [32]:
np.where(np.logical_and(a>=3, a<=7))

(array([3, 4, 5, 6, 7], dtype=int64),)

In [33]:
a[a == 3]

array([3])